package me.vasuki.productservice.model;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Data
@Builder
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
@Table(name = "orders")
public class Product {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")  // Optional: specify column name
    private Long id;

    @Column(name = "name", nullable = false, length = 100)  // Specify column name, not null, and length
    private String name;

    @Column(name = "description", length = 255)  // Specify column name and length
    private String description;

    @Column(name = "price", nullable = false)  // Specify column name and not null
    private double price;

    @Column(name = "stock", nullable = false)  // Specify column name and not null
    private int stock;

    @Column(name = "image_id", nullable = false, length = 50)
    private String imageId;  // New field for image ID
    // Getters and setters are generated by Lombok annotations
}
